### ISSUE TITLE
Develop issue on IntelliJ IDEA IDE

### ISSUE THREAD

**Issue by dnalm** [nivanov/cosplay#116]
![image](https://user-images.githubusercontent.com/9978230/205351104-695feecb-8093-44f5-a8f2-8c176807aac9.png)

When I read the code on the IDEA ide, the hint of the editor is messed up, and the auto-complete function is broken.

Are there any configurations I need to set?

Thank you.

**Comment by nivanov** [comment]
I'm having similar issues... I suspect (although can't guarantee) it has something to do with having both pom.xml and build.sbt in the same project. Something is screwing up IDEA... Unfortunately, we have to maintain both Maven and SBT as we use them both in release process at this moment.
