### ISSUE TITLE
Default font has non-zero spacing between characters

### ISSUE THREAD

**Issue by Educorreia932** [nivanov/cosplay#84]
When using default Monospaced font in Windows 10 and JDK 17, there's a spacing between characters that breaks continuity of elements such as lines.

<p align="center">
    <img width=350 src=https://user-images.githubusercontent.com/44172778/172196434-f9ead89c-fc17-4ccc-ac73-53b098e5c95c.png>
</p>

This, however, doesn't happen in macOS, probably because it's using a different font.

<p align="center">
    <img width=350 src=https://user-images.githubusercontent.com/44172778/172196461-8ef5c681-725c-4314-9eee-d85549673de7.png>
</p>

Changing `COSPLAY_EMUTERM_CH_HEIGHT_OFFSET` and `COSPLAY_EMUTERM_CH_WIDTH_OFFSET` doesn't solve this issue, since the existing spacing goes all around the character and the offset would only go for one direction.

Using a different font would solve this, but I've struggled to find a font with wide support of Unicode characters and, at the same time, pleasant appearance.

Changing the [`TextAttribute.TRACKING`](https://docs.oracle.com/javase/7/docs/api/java/awt/font/TextAttribute.html) value of the font would probably work.

**Comment by nivanov** [comment]
Not sure this addresses it but you can use following system properties (see http://cosplayengine.com/devguide/game_structure.html#system-props):
- COSPLAY_EMUTERM_CH_WIDTH_OFFSET
- COSPLAY_EMUTERM_CH_HEIGHT_OFFSET

**Comment by nivanov** [comment]
Also, if you can provide OS/JVM/Font name you are using along with a screenshot - that would help.

**Comment by Educorreia932** [comment]
> Not sure this addresses it but you can use following system properties (see http://cosplayengine.com/devguide/game_structure.html#system-props):
> 
> * COSPLAY_EMUTERM_CH_WIDTH_OFFSET
> * COSPLAY_EMUTERM_CH_HEIGHT_OFFSET
> 
> to change how fonts are rendered in the terminal emulator. Or... use different font all together.
> Also, if you can provide OS/JVM/Font name you are using along with a screenshot - that would help.

I've edited the issue's original description to add more information and answer your questions

**Comment by nivanov** [comment]
Here's couple of thoughts on this issue.

1. This only applies to built-in CosPlay terminal emulation. If you play the game natively, i.e. in ANSI terminal - there's no way to control the font. You can theoretically ask the user to install & use a certain font - but the chances of that actually done are pretty slim. Again - there's no technical way to change (or even know) the font that used by the native terminal.

2. I've played with TextAttribute.TRACKING and it has zero effect on the default font used (Monospace). Moreover (see p.1) even if it would work It may be perceived as a slight cheating as the game will certainly look different in the native terminal. 

2.1 I'm typing this on MacOS and I don't get the same smoothness on the font as you do ( at least using the default CosPlay terminal emulator font).
